### ISSUE TITLE
Option to hand list of values for parameters in ``model_setup`` for ``parameter_experiments.py``

### ISSUE THREAD

**Issue by nilsnevertree** [nilsnevertree/reconstruct-climate-indices#25]
Add option to set a list of values that shall be used for the parameter experiment.
This allows more flexiblity compared to the given *multiply original values by factor*.

This could look like this:
````yaml
model_setup :
    # The model function used for all experiments
    model_function : "idealized_ocean.AMO_oscillatory_ocean"
    # 1. step
    # dictonary containing the default settings that shall later be modified.
    default_settings : {
            nt: 3000,  # timesteps in 50 * 12
            dt: 30,  # days
            per0: 8766,    # days 8766 = 24 * 365.25
            tau0: 3652.5,  # days 3652.5 = 10* 365.25
            dNAO: 0.1,
            dEAP: 0.1,
            cNAOvsEAP: 0,
            seed: 331381460666,
        }
    ### The parameter_experiment.py file will create all combinations of parameters provided with the following settings in the model_setup dictonary.
    # 2. step
    # The values of the modified arguments will be multiplicated by the factors provided below.
    modified_arguments : ["dNAO", "dEAP"]
    factors :  [0.5, 1, 2]
    numpy_round_factor : 6 # factor will be used as rounding for all changes settings using the factor list.
    # 3. step
    # The values in default settings and given by the modified arguemtns (step 2) will be OVERRIDEN by the lists provided in this dictonary.
    modified_settings : {
        seed : [
            331381460666, # Default value of the idealized_ocean functions.
            # 281919096187,
            # 841890021701,
            # 573526330895,
            # 729014145638,
            # 831545864661,
            # 379772175813,
            # 68282207887,
            # 326575964518,
            # 486318926357,
        ]
    }


````
