### ISSUE TITLE
Add latent variables iteratively.

### ISSUE THREAD

**Issue by nilsnevertree** [nilsnevertree/reconstruct-climate-indices#43]
It is more convenient to add latent variables iteratively to the Kalman-SEM.
Therefore, this should be implemented.

For instance, by providing a flag:
````yaml
random_setup:
   iterative : true
   ...
````

To do this, child runs should be used by mlflow.
This is well shown here: https://stackoverflow.com/a/67160579/16372843
